#pragma once

#include "devils/devilLib/devils.h"
#include "../subsystems/liftSystem.hpp"
#include "../subsystems/clawSystem.hpp"
#include "devils/devilLib/geometry/units.hpp"
#include "liftStep.hpp"

namespace devils
{
    class MoaSkillsAutoNew
    {
    public:
        static void run(SwerveChassis& chassis, OdomSource& odometry, LiftSystem& lift, ClawSystem& claw)
        {
            TrajectoryConstraints::defaultConstraints = TrajectoryConstraints{
                .maxVelocity = 15.0f
            };
            const auto liftStep = std::make_shared<LiftStep>(lift, 0, 31.0f);
            liftStep->start();

            // Blaze starts pressed against the wall, facing the field,
            // beneath the red alliance station toggle,
            // Blaze's right side should be 3 inches left of the center line's left side

            // =====================================
            //     moaSkillsAuto
            //     Originally Generated by AutoDevil 0.3.1, very modified
            //     https://auto.devilbots.org/
            // =====================================

            AutoBuilder autoBuilder = AutoBuilder(chassis, odometry);

            // TOGGLE
            autoBuilder.jumpTo({-62.5, -10, Units::degToRad(0)});
            autoBuilder.driveToHolonomic({-54, -3, Units::degToRad(0)}, Units::degToRad(180), Units::degToRad(0))->startSync();
            liftStep->setPositionsToMove(2);
            autoBuilder.driveToHolonomic({-62, -3, Units::degToRad(0)}, Units::degToRad(0), Units::degToRad(0))->startSync();
            autoBuilder.driveToHolonomic({-54, -3, Units::degToRad(0)}, Units::degToRad(180), Units::degToRad(0))->startSync();
            autoBuilder.rotateTo(-30)->startSync();

            // SCORE FIRST
            autoBuilder.driveToHolonomic({-51, -19, Units::degToRad(-30)}, Units::degToRad(-30+180), Units::degToRad(-30))->startSync();
            liftStep->setPositionsToMove(-1.5);
            pros::delay(1000);
            claw.setClawClosed(true); // open claw
            autoBuilder.driveTo({-60, 3, Units::degToRad(-45)})->startSync();
            autoBuilder.rotateTo(135)->startSync();
            liftStep->setPositionsToMove(-3); // make sure lift is bottomed out, clamp handles this

            // MATCHLOAD AND SCORE SECOND
            autoBuilder.driveTo({-24, -24, Units::degToRad(135)})->startSync();
            autoBuilder.driveTo({-58, -44, Units::degToRad(-180)})->startSync();
            autoBuilder.driveTo({-50, -55, Units::degToRad(-270)})->startSync();
            autoBuilder.driveTo({-50, -59, Units::degToRad(-180)})->startSync();
            autoBuilder.driveTo({-63.5, -59, Units::degToRad(-180)})->startSync();
            claw.setClawClosed(false); // claw close
            pros::delay(300);
            autoBuilder.driveTo({-53.94, -57.6, Units::degToRad(-180)})->startSync();
            
            liftStep->setPositionsToMove(2.5);
            autoBuilder.driveTo({-48, -29.5, Units::degToRad(90)})->startSync();
            liftStep->setPositionsToMove(-1.4);
            pros::delay(1000);
            claw.setClawClosed(true); // claw open
            autoBuilder.driveTo({-43.219, -59.94, Units::degToRad(-180)})->startSync();
            liftStep->setPositionsToMove(-5); // make sure lift is bottomed out, clamp handles this

            // MATCHLOAD AND SCORE THIRD
            autoBuilder.driveTo({-63.5, -57.6, Units::degToRad(-180)})->startSync();
            claw.setClawClosed(false); // claw close
            pros::delay(300);
            autoBuilder.driveTo({-53.94, -57.6, Units::degToRad(-180)})->startSync();
            
            liftStep->setPositionsToMove(2.5);
            autoBuilder.driveTo({-48, -29, Units::degToRad(90)})->startSync();
            liftStep->setPositionsToMove(-1.4);
            pros::delay(1000);
            claw.setClawClosed(true); // claw open
            autoBuilder.driveTo({-43.219, -59.94, Units::degToRad(-180)})->startSync();
            liftStep->setPositionsToMove(-5); // make sure lift is bottomed out, clamp handles this

            // MATCHLOAD AND SCORE FOURTH
            autoBuilder.driveTo({-59.94, -59.94, Units::degToRad(-180)})->startSync();
            // claw close
            // lift +2 pos
            autoBuilder.driveTo({-34.987, -47.592, Units::degToRad(0)})->startSync();
            // lift -1 pos
            // claw open
            autoBuilder.driveTo({-43.219, -60.198, Units::degToRad(-180)})->startSync();
            // lift -1 pos

            // MATCHLOAD AND SCORE FIFTH
            autoBuilder.driveTo({-59.94, -60.455, Units::degToRad(180)})->startSync();
            // claw close
            // lift +3 pos
            autoBuilder.driveTo({-35.244, -47.849, Units::degToRad(0)})->startSync();
            // lift -1 pos
            // claw open
            autoBuilder.driveTo({-43.476, -59.683, Units::degToRad(-180)})->startSync();
            // lift - 2 pos

            // MATCHLOAD AND SCORE SIXTH
            autoBuilder.driveTo({-59.94, -60.198, Units::degToRad(180)})->startSync();
            // claw close
            // lift + 4 pos
            autoBuilder.driveTo({-35.244, -47.592, Units::degToRad(0)})->startSync();
            // lift -1 pos
            // claw open
            autoBuilder.driveTo({-41.161, -47.849, Units::degToRad(0)})->startSync();
            // lift -3 pos

            // TOGGLE AND MOVE TO MIDDLE
            autoBuilder.rotateTo(-45)->startSync();
            autoBuilder.driveTo({0.257, -52.737, Units::degToRad(90)})->startSync();
            autoBuilder.driveTo({0, -63.799, Units::degToRad(90)})->startSync();
            autoBuilder.driveTo({-0.257, -13.12, Units::degToRad(90)})->startSync();

            // =====================================
            //     End of moaSkillsAuto
            // =====================================
    
        }
    };
}
