#pragma once

#include "devils/devilLib/devils.h"
#include "../subsystems/liftSystem.hpp"
#include "../subsystems/clawSystem.hpp"
#include "liftStep.hpp"

namespace devils
{
    class TestingAuto
    {
    public:
        static void run(SwerveChassis& chassis, OdomSource& odom, LiftSystem& lift, ClawSystem& claw)
        {
            TrajectoryConstraints::defaultConstraints = TrajectoryConstraints{
                .maxVelocity = 40.0f
            };
            const auto liftStep = std::make_shared<LiftStep>(lift, 0, 31.0f);
            liftStep->start();

            // auto autoBuilder = AutoBuilder(chassis, odom);
            // autoBuilder.jumpTo({0, 0, Units::degToRad(180)});
            // autoBuilder.rotateTo(360)->startSync();
            // liftStep->setPositionsToMove(3.0f);
            // autoBuilder.driveTo({-24, 24, Units::degToRad(0)})->startSync();
            // claw.setClawClosed(true);
            // pros::delay(500);
            // liftStep->setPositionsToMove(-3.0f);
            // autoBuilder.driveTo({-24, -24, Units::degToRad(180)})->startSync();

            // autoBuilder.driveTo({-24, -24, Units::degToRad(0)})->startSync();
            // autoBuilder.driveTo({24, -24, Units::degToRad(0)})->startSync();
            // autoBuilder.driveTo({24, 24, Units::degToRad(0)})->startSync();
            //autoBuilder.rotate(180);


            // =====================================
            //     AutoDevilTest
            //     Generated by AutoDevil 0.3.1
            //     https://auto.devilbots.org/
            // =====================================

            AutoBuilder autoBuilder = AutoBuilder(chassis, odom);
            autoBuilder.jumpTo({0.263, 0.041, Units::degToRad(-90)});
            autoBuilder.driveTo({-24.439, -23.925, Units::degToRad(90)})->startSync();
            autoBuilder.driveTo({23.41, -22.124, Units::degToRad(90)})->startSync();
            autoBuilder.driveTo({23.925, 23.667, Units::degToRad(90)})->startSync();
            autoBuilder.driveTo({-24.439, 23.153, Units::degToRad(90)})->startSync();

            // =====================================
            //     End of AutoDevilTest
            // =====================================
        }
    };
}
