#pragma once
#include "devils/devils.h"

namespace devils
{
    class MatchAuto
    {
        static void run(BaseChassis& chassis,    
                        OdomSource& odom)
        {
            // =====================================
            //     WIP Match Auto
            //     Generated by AutoDevil 0.3.1
            //     https://auto.devilbots.org/
            // =====================================

            AutoBuilder autoBuilder = AutoBuilder(chassis, odom);
            autoBuilder.jumpTo({-64, 16, 0});
            autoBuilder.driveTo({-13, 13, -45})->startSync();
            pros::delay(9999999);
            // Drop off balls
            autoBuilder.driveTo({-48, 48, -45})->startSync();
            autoBuilder.rotateTo(180)->startSync();
            autoBuilder.driveTo({-60, 48, 180})->startSync();
            // Pickup Loader
            autoBuilder.driveTo({-32, 48, 180})->startSync();
            // Drop off balls
            autoBuilder.driveTo({-40, 44, 247.5})->startSync();
            autoBuilder.rotateTo(135)->startSync();
            // Drop wing mech, drop blue blocks
            autoBuilder.driveTo({-10, 37, 180})->startSync();
            autoBuilder.driveTo({-38, 42, 135})->startSync();
            autoBuilder.driveTo({-60, 48, 180})->startSync();
            // Pickup loader blocks
            autoBuilder.driveTo({-32, 48, 180})->startSync();
            // SLAM IT! (and hold)

            // =====================================
            //     End of WIP Match Auto
            // =====================================
        }
    };
}