#pragma once

#include "devils/devils.h"
#include "../subsystems/StickSystem.hpp"
#include "../subsystems/intakeSystem.hpp"
#include "../subsystems/tubeSystem.hpp"
#include "../subsystems/wingSystem.hpp"
#include "stickAutoStep.hpp"
#include "autoIntakeStep.hpp"

namespace devils
{
    class TubeSystem;
    class IntakeSystem;

    class MatchAuto
    {
    public:
        static void run(TankChassis& chassis,
                        OdomSource& odom,
                        StickSystem& stick,
                        IntakeSystem& intake,
                        TubeSystem& tube,
                        WingSystem& wings,
                        const bool isRight = false)
        {
            TrajectoryConstraints::defaultConstraints = TrajectoryConstraints{
                .maxVelocity = 50.0f
            };

            const auto stickAutoStep = std::make_shared<StickAutoStep>(stick);
            stickAutoStep->start();

            const auto intakeAutoStep = std::make_shared<AutoIntakeStep>(intake, stick);
            intakeAutoStep->start();

            // =====================================
            //     WIP Match Auto
            //     Generated by AutoDevil 0.3.1
            //     https://auto.devilbots.org/
            // =====================================

            auto autoBuilder = AutoBuilder(chassis, odom);

            if (isRight)
            {
                autoBuilder.setPoseTransformer(std::make_unique<MirrorTransformY>());
                autoBuilder.jumpTo({-46, -14, Units::degToRad(0)});
            }
            else
                autoBuilder.jumpTo({-46, -14, Units::degToRad(180)});
            tube.setTubeRaised(true);


            // 0. Deploy PJ
            /*if (isRight)
            {
                tube.setTubeRaised(true);
                wings.setWingRaised(true);
            } */

            // Drop off at center goal
            stick.homeStick();
            //deploy pj
            if (isRight)
            {
                tube.setTubeRaised(true);
                //opwn hood later
                //stick.setState(StickSystem::State::EXTEND_FOR_PJ_DEPLOY);
            }  
            //drives to center goal, pj faces forwards
            if (isRight)
                autoBuilder.driveTo({-14.5f, -11, Units::degToRad(45)})->startSync();
            else
                autoBuilder.driveTo({-15, -12, Units::degToRad(225)})->startSync();
            stick.setState(StickSystem::State::RETRACTED);
            
            //score center goal, pj uses intake
            if (isRight)
            {
                intake.setArmsExtended(true);
                intakeAutoStep->setTargetSpeed(-1.0f);
                pros::delay(1000);
            }
            else
            {
                tube.setTubeRaised(false);
                wings.setWingRaised(false);
                stick.setState(StickSystem::State::EXTENDED_FAST);
                pros::delay(1000);
            }

            // Move to loader
            stick.setState(StickSystem::State::RETRACTED);
            intake.setArmsExtended(true);
            if (isRight)
            {
                stick.setState(StickSystem::State::EXTENDED_FAST);
                pros::delay(500);
                tube.setTubeRaised(false);
                autoBuilder.driveTo({-19.5, -16, Units::degToRad(45)})->startSync();
                stick.setState(StickSystem::State::RETRACTED);
                tube.setTubeRaised(true);
                const auto backupFromGoalStep = autoBuilder.driveTo({-50, -42, Units::degToRad(180)}, 40.0f)->start();
                pros::delay(100);
                intakeAutoStep->setTargetSpeed(1.0f);
                autoBuilder.rotateTo(180)->startSync();
                tube.setTubeRaised(true);
                backupFromGoalStep->join();
            }
            else
            {
                const auto backupFromGoalStep = autoBuilder.driveTo({-50, -43, Units::degToRad(180)}, 40.0f)->start();
                pros::delay(100);
                intakeAutoStep->setTargetSpeed(1.0f);
                backupFromGoalStep->join();
                autoBuilder.rotateTo(180)->startSync();
                tube.setTubeRaised(true);
            }
            autoBuilder.driveTo({-62, isRight ? -42 : -43.0f, Units::degToRad(180)})->startSync();

            // Wiggle while picking up from loader
            wiggle(chassis, 3.5f, 0.2f);

            // Move to long goal
            autoBuilder.rotateTo(180)->startSync();
            autoBuilder.driveTo({-37, isRight ? -41.5f : -43.0f, Units::degToRad(180)})->startSync();
            scoreInLongGoal(chassis, stick, StickSystem::State::EXTEND_FOR_THREE);

            // Spit blocks
            autoBuilder.driveTo({-45, isRight ? -40 : -42.0f, Units::degToRad(180)})->startSync();
            intakeAutoStep->setTargetSpeed(-1.0f);
            autoBuilder.rotateTo(300)->startSync();
            stick.setState(StickSystem::State::EXTENDED_FAST);
            autoBuilder.rotateTo(180)->startSync();
            stick.setState(StickSystem::State::RETRACTED);
            intakeAutoStep->setTargetSpeed(1.0f);

            // Move to loader
            autoBuilder.driveTo({-60, isRight ? -41 : -43.0f, Units::degToRad(180)})->startSync();
            wiggle(chassis, 3.5f, 0.2f);

            // Score in long goal
            autoBuilder.rotateTo(180)->startSync();
            autoBuilder.driveTo({-37, isRight ? -42.5f : -44.0f, Units::degToRad(180)})->startSync();
            scoreInLongGoal(chassis, stick);
            stick.setState(StickSystem::State::EXTENDED_FAST);

            // =====================================
            //     End of WIP Match Auto
            // =====================================
        }

        static void wiggle(TankChassis& chassis, const float duration, const float magnitude = 0.15f)
        {
            auto wiggleTimer = Timer(duration);
            wiggleTimer.start();

            while (!wiggleTimer.getIsFinished())
            {
                chassis.move(0.1f, 0.15f, 0);
                pros::delay(100);
                chassis.move(0.1f, -0.15f, 0);
                pros::delay(100);
                chassis.stop();
                pros::delay(300);

                if (wiggleTimer.getIsFinished())
                    break;


                chassis.move(0.1f, -magnitude, 0);
                pros::delay(200);
                chassis.stop();
                pros::delay(300);
                chassis.move(0.1f, magnitude, 0);
                pros::delay(200);
                chassis.stop();
                pros::delay(300);
            }
        }

        static void scoreInLongGoal(
            TankChassis& chassis,
            StickSystem& stick,
            const StickSystem::State targetState = StickSystem::State::EXTENDED_SLOW)
        {
            // Apply pressure
            chassis.move(-0.1f, 0, 0);

            // Extend stick
            stick.setState(targetState);
            pros::delay(1000);
            stick.setState(StickSystem::State::RETRACTED);
            pros::delay(500);
            stick.setState(targetState);
            pros::delay(1000);
            stick.setState(StickSystem::State::RETRACTED);
        }
    };
}
