#pragma once
#include "devils/devils.h"

namespace devils
{
    class MatchAuto
    {
        static void run(BaseChassis& chassis,    
                        OdomSource& odom)
        {
            // =====================================
            //     WIP Match Auto
            //     Generated by AutoDevil 0.3.1
            //     https://auto.devilbots.org/
            // =====================================

            AutoBuilder autoBuilder;
            autoBuilder.jumpTo({-46, -14, 540});
            autoBuilder.driveTo({-13, -13, 225})->startSync();
            // Drop off balls
            autoBuilder.driveTo({-48, -48, 225})->startSync();
            autoBuilder.rotateTo(180)->startSync();
            autoBuilder.driveTo({-60, -48, 180})->startSync();
            // Pickup Loader
            autoBuilder.driveTo({-32, -48, 180})->startSync();
            // Drop off balls
            autoBuilder.driveTo({-44, -40, 135})->startSync();
            autoBuilder.rotateTo(225)->startSync();
            autoBuilder.driveTo({-10, -37, 180})->startSync();
            // Drive through
            autoBuilder.driveTo({-40, -41, 225})->startSync();
            autoBuilder.driveTo({-60, -48, 180})->startSync();
            autoBuilder.driveTo({-32, -48, 180})->startSync();
            // Drop off bloalls

            // =====================================
            //     End of WIP Match Auto
            // =====================================
        }
    };
}