#pragma once

#include "devils/devils.h"
#include "matchAuto.hpp"

namespace devils
{
    class SkillsAuto
    {
    public:
        static void run(TankChassis& chassis,
                        OdomSource& odom,
                        StickSystem& stick,
                        IntakeSystem& intake,
                        TubeSystem& tube)
        {
            // const auto stickAutoStep = std::make_shared<StickAutoStep>(stick);
            // stickAutoStep->start();
            //
            // const auto intakeAutoStep = std::make_shared<AutoIntakeStep>(intake, stick);
            // intakeAutoStep->start();
            //
            // // =====================================
            // //     Skills Auto (Purdue Slam & Jam)
            // //     Generated by AutoDevil 0.3.1
            // //     https://auto.devilbots.org/
            // // =====================================
            //
            // const auto autoBuilder = AutoBuilder(chassis, odom);
            // odom.setPose({-44, -14, Units::degToRad(0)});
            // stick.homeStick();
            //
            // // 1. Pickup N Blocks
            // auto step1 = autoBuilder.driveTo({0, -34, Units::degToRad(-90)})->start();
            // pros::delay(1000);
            // intake.setArmsExtended(true);
            // step1->join();
            //
            // // 2. Center Goal
            // autoBuilder.driveTo({-16, -22, Units::degToRad(0)})->startSync();
            // autoBuilder.rotateTo(225)->startSync();
            // autoBuilder.driveTo({-14, -19, Units::degToRad(225)})->startSync();
            //
            // stick.setState(StickSystem::State::EXTENDED_SLOW);
            // pros::delay(800);
            // tube.setTubeRaised(true);
            // pros::delay(500);
            // stick.setState(StickSystem::State::RETRACTED);
            //
            // // 3. NW Loader
            // intake.setArmsExtended(true);
            // autoBuilder.driveTo({-48, -48, Units::degToRad(180)}, 40.0f)->startSync();
            // autoBuilder.driveTo({-58.5f, -48, Units::degToRad(180)})->startSync();
            // MatchAuto::wiggle(chassis, 3.0f);
            //
            // // 4. N Long Goal
            // autoBuilder.driveTo({-33, -60, Units::degToRad(180)}, 40.0f)->startSync();
            // autoBuilder.driveTo({39, -60, Units::degToRad(180)}, 40.0f)->startSync();
            // autoBuilder.driveTo({45, -49, Units::degToRad(360)}, 20.0f)->startSync();
            // autoBuilder.driveTo({32, -49, Units::degToRad(360)})->startSync();
            // scoreInLongGoal(chassis, stick);
            //
            // // 5. NE Loader
            // autoBuilder.driveTo({57, -48, Units::degToRad(0)})->startSync();
            // MatchAuto::wiggle(chassis, 3.0f);
            //
            // // 6. N Long Goal
            // autoBuilder.driveTo({32, -49, Units::degToRad(0)})->startSync();
            // scoreInLongGoal(chassis, stick);
            // intake.setArmsExtended(false);
            //
            // // 7. NE Blocks
            // // auto step7 = autoBuilder.driveTo({48, -63, Units::degToRad(270)})->startSync();
            // // pros::delay(1000);
            // // intake.setArmsExtended(true);
            // // step7->join();
            // // pros::delay(1000);
            // //
            // // // 8. N Long Goal
            // // autoBuilder.driveTo({32, -52, Units::degToRad(0)})->startSync();
            // // scoreInLongGoal(chassis, stick);
            //
            // // 9. Park (and clear parking zone)
            // autoBuilder.driveTo({43, -33, Units::degToRad(135)}, 10.0f)->startSync();
            // autoBuilder.driveTo({20, -28, Units::degToRad(-180)}, 40.0f)->startSync();
            // autoBuilder.driveTo({-43, -32, Units::degToRad(180)}, 40.0f)->startSync();
            // autoBuilder.driveTo({-67, -20, Units::degToRad(90)}, 40.0f)->startSync();
            // autoBuilder.driveTo({-67, -17, Units::degToRad(90)}, 40.0f)->startSync();

            intake.setArmsExtended(true); // <-- Clear out blocks in park zone
            tube.setTubeRaised(true); // <-- Fit Blaze next to PJ

            // Align to park zone
            chassis.move(0.2f, 0, 0);
            pros::delay(500);
            chassis.stop();
            pros::delay(200);

            // Go over initial hump
            chassis.move(0.4f, 0, 0);
            pros::delay(800);

            // Slow down for second hump
            chassis.move(0.2f, 0, 0);
            pros::delay(1500);
            chassis.stop();

            // =====================================
            //     End of Skills Auto - Purdue
            // =====================================
        }

        static void scoreInLongGoal(TankChassis& chassis, StickSystem& stick)
        {
            // Apply pressure
            chassis.move(-0.1f, 0, 0);

            // Extend stick
            stick.setState(StickSystem::State::EXTENDED_FAST);

            // Wait for stick to be fully extended
            pros::delay(1000);

            // Retract stick
            stick.setState(StickSystem::State::RETRACTED);
        }
    };
}
