#pragma once

#include "devils/devils.h"
#include "matchAuto.hpp"
#include "../subsystems/wingSystem.hpp"

namespace devils
{
    class SkillsAuto
    {
    public:
        static void run(TankChassis& chassis,
                        OdomSource& odom,
                        StickSystem& stick,
                        IntakeSystem& intake,
                        TubeSystem& tube,
                        WingSystem& wings,
                        const bool isRight = false)
        {
            auto defaultSpeed = TrajectoryConstraints::defaultConstraints;
            auto slowSpeed = TrajectoryConstraints{.maxVelocity = 8.0f};

            const auto stickAutoStep = std::make_shared<StickAutoStep>(stick);
            stickAutoStep->start();

            const auto intakeAutoStep = std::make_shared<AutoIntakeStep>(intake, stick);
            intakeAutoStep->start();
            intakeAutoStep->setTargetSpeed(1.0f);

            // =====================================
            //     Skills Auto (Purdue Slam & Jam)
            //     Generated by AutoDevil 0.3.1
            //     https://auto.devilbots.org/
            // =====================================

            auto autoBuilder = AutoBuilder(chassis, odom);

            if (isRight)
                autoBuilder.setPoseTransformer(std::make_unique<MirrorTransformY>());

            if (!isRight)
                autoBuilder.jumpTo({-44, -14, Units::degToRad(0)});
            else
                autoBuilder.jumpTo({-44, -14, Units::degToRad(0)});
            stick.homeStick();

            // 0. Deploy PJ
            if (isRight)
            {
                tube.setTubeRaised(true);
                wings.setWingRaised(true);
            }

            // 1. Pickup N Blocks
            autoBuilder.driveTo({-6, -18, Units::degToRad(0)})->startSync();

            tube.setTubeRaised(false);
            wings.setWingRaised(false);

            TrajectoryConstraints::defaultConstraints = slowSpeed;
            autoBuilder.driveTo({2, -24, Units::degToRad(-90)})->startSync();
            autoBuilder.driveTo({2, -48, Units::degToRad(-90)})->startSync();
            TrajectoryConstraints::defaultConstraints = defaultSpeed;
            intake.setArmsExtended(true);
            pros::delay(500);


            // 2. Center Goal
            if (!isRight)
            {
                autoBuilder.driveTo({-11, -20.5, Units::degToRad(0)})->startSync();
                tube.setTubeRaised(true);

                autoBuilder.rotateTo(220)->startSync();
                //autoBuilder.driveTo({-10, -16, Units::degToRad(220)})->startSync();

                tube.setTubeRaised(false);
                pros::delay(200);
                stick.setState(StickSystem::State::EXTENDED_SLOWER);
                pros::delay(1000);
                stick.setState(StickSystem::State::RETRACTED);
                pros::delay(400);
                stick.setState(StickSystem::State::EXTENDED_SLOWER);
                pros::delay(1000);
                stick.setState(StickSystem::State::RETRACTED);
                tube.setTubeRaised(true);

                autoBuilder.driveTo({-48, -48, Units::degToRad(180)}, 40.0f)->startSync();
            }
            else
            {
                auto step2 = autoBuilder.driveTo({-14, -21, Units::degToRad(0)})->start();
                pros::delay(500);
                tube.setTubeRaised(true);
                step2->join();

                autoBuilder.rotateTo(45)->startSync();
                autoBuilder.driveTo({-12.5f, -16, Units::degToRad(45)})->startSync();
                intakeAutoStep->setTargetSpeed(-0.9f);
                pros::delay(2500);
                intakeAutoStep->setTargetSpeed(1.0f);

                autoBuilder.driveTo({-14, -21, Units::degToRad(0)})->startSync();
                stick.setState(StickSystem::State::EXTENDED_FAST);
                pros::delay(250);
                tube.setTubeRaised(false);
                //autoBuilder.driveTo({-19.5, -16, Units::degToRad(45)})->startSync();
                pros::delay(400);
                stick.setState(StickSystem::State::RETRACTED);
                tube.setTubeRaised(true);
                autoBuilder.rotateTo(230)->startSync();
            }

            // 3. NW Loader
            if (!isRight)
            {
                intake.setArmsExtended(true);
                autoBuilder.driveTo({-58.5f, -49, Units::degToRad(180)})->startSync();
                MatchAuto::wiggle(chassis, 4.0f);
            }
            else
            {
                intake.setArmsExtended(true);
                autoBuilder.driveTo({-58.5f, -48, Units::degToRad(180)})->startSync();
                MatchAuto::wiggle(chassis, 4.0f);
            }


            // 4. N Long Goal
            autoBuilder.driveTo({-33, isRight ? -63.0f : -63.0f, Units::degToRad(180)}, 40.0f)->startSync();
            autoBuilder.driveTo({39, -62, Units::degToRad(180)})->startSync();
            autoBuilder.driveTo({45, isRight ? -51 : -48.5f, Units::degToRad(360)}, 20.0f)->startSync();
            autoBuilder.rotateTo(360)->startSync();
            autoBuilder.driveTo({33, isRight ? -50.5f : -48.5f, Units::degToRad(360)})->startSync();
            scoreInLongGoal(chassis, stick);

            // 5. NE Loader
            autoBuilder.driveTo({62, isRight ? -49.0f : -51.0f, Units::degToRad(0)})->startSync();
            MatchAuto::wiggle(chassis, 4.0f);

            // 6. N Long Goal
            autoBuilder.driveTo({34, isRight ? -51 : -49.0f, Units::degToRad(0)})->startSync();
            scoreInLongGoal(chassis, stick);
            intake.setArmsExtended(false);

            // 7. Park (and clear parking zone)
            if (!isRight)
            {
                autoBuilder.driveTo({56, -42, Units::degToRad(0)})->startSync();
                autoBuilder.driveTo({30, -28, Units::degToRad(0)}, 40.0f)->startSync();
                autoBuilder.driveTo({-40, -38, Units::degToRad(0)}, 40.0f)->startSync();
                autoBuilder.driveTo({-56, -22, Units::degToRad(-90)}, 20.0f)->startSync();
                autoBuilder.driveTo({-57, -18, Units::degToRad(-90)})->startSync();

                intake.setArmsExtended(false);
                tube.setTubeRaised(false);

                // Align to park zone
                chassis.move(-0.2f, 0, 0);
                pros::delay(1000);

                // Backup for speed
                chassis.move(0.2f, 0, 0);
                pros::delay(200);

                // Go over initial hump
                chassis.move(-0.6f, 0, 0);
                pros::delay(800);

                // Slow down for second hump
                chassis.move(-0.2f, 0, 0);
                pros::delay(900);
                chassis.stop();
            }
            else
            {
                autoBuilder.driveTo({56, -58, Units::degToRad(-65)})->startSync();
                autoBuilder.driveTo({66.5f, -17, Units::degToRad(-90)})->startSync();

                // Align to park zone
                chassis.move(-0.2f, 0, 0);
                pros::delay(1000);

                // Backup for speed
                chassis.move(0.2f, 0, 0);
                pros::delay(200);

                // Go over initial hump
                chassis.move(-0.6f, 0, 0);
                pros::delay(800);

                // Drive over second hump
                chassis.move(-0.4f, 0, 0);
                pros::delay(1000);
                chassis.stop();

                pros::delay(1000);
                autoBuilder.jumpToWithoutRotation({64, 32});
                autoBuilder.driveTo({40, 38, Units::degToRad(45)})->startSync();
                autoBuilder.driveTo({-40, 36, Units::degToRad(0)}, 40.0f)->startSync();
                autoBuilder.driveTo({-62.0f, 20, Units::degToRad(90)}, 20.0f)->startSync();
                autoBuilder.driveTo({-63.0f, 16, Units::degToRad(90)})->startSync();

                // Align to park zone
                chassis.move(-0.2f, 0, 0);
                pros::delay(1000);

                // Backup for speed
                chassis.move(0.2f, 0, 0);
                pros::delay(200);

                // Go over initial hump
                chassis.move(-0.6f, 0, 0);
                pros::delay(500);
                chassis.stop();
            }

            // =====================================
            //     End of Skills Auto - Purdue
            // =====================================
        }

        static void scoreInLongGoal(TankChassis& chassis, StickSystem& stick)
        {
            // Apply pressure
            chassis.move(-0.1f, 0, 0);

            // Extend stick
            stick.setState(StickSystem::State::EXTENDED_SLOW);
            pros::delay(1000);
            stick.setState(StickSystem::State::RETRACTED);
            pros::delay(500);
            stick.setState(StickSystem::State::EXTENDED_SLOW);
            pros::delay(1000);

            // Retract stick
            stick.setState(StickSystem::State::RETRACTED);
        }
    };
}
